# Generated by Django 4.2.5 on 2023-09-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataForChart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('data', models.JSONField()),
                ('parsed_file_path', models.CharField(max_length=255)),
            ],
        ),
    ]
